import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import React from 'react';

const Web3Utils = require('web3-utils');

const Home: NextPage = () => {
  const [bn, setBn] = React.useState('');
  const [drawing, setDrawing] = React.useState<boolean>(false);
  const [grid, setGrid] = React.useState<number[]>([...Array(2304)].fill(0));

  // let grid = [...Array(2304)].map( (x,i) => {
  //   const evenRow = (Math.floor(i /48)) % 2 == 0;
  //   if (evenRow) return i % 2 ? 1:0 
  //   else return i % 2 ? 0:1 ;
  // })
  // let grid = [...Array(2304)].fill(0);



  const clickPixel = (event: any, i: number) => {
    let g = grid;
    g[i] = 1;
    console.log(g)
    setGrid(g);
    event.currentTarget.style.backgroundColor = 'salmon';
    updateBN()
  }

  const fillPixel = (event: any, i: number) => {

    if(drawing) {
      let g = grid;
      g[i] = 1;
      console.log(g)
      setGrid(g);
      event.currentTarget.style.backgroundColor = 'salmon';
      updateBN()
    }
  }

  const startDraw = () => {
    setDrawing(true)
  }

  const endDraw = () => {
    setDrawing(false)
  }

  
  const updateBN = () => {
    const number = new Web3Utils.BN(0); 
    grid.forEach((n, i) => number.setn(i, n));
    setBn(number.toString())
  }


  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          name="description"
          content="Generated by @rainbow-me/create-rainbowkit"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.grid}>
          {grid.map((x, i) => 
              <div
                onClick={(event) => clickPixel?.(event, i )}
                onMouseDown={() => startDraw() }
                onMouseUp={() => endDraw() }
                onMouseEnter={(event) => fillPixel?.(event, i ) }
                style={{ backgroundColor: x == 1 ? '#333' : '#fafafa'}}
                key={i}
                className={styles.gridItem}></div>
          )}
        </div>
        <div>
          <p>{bn}</p>
        </div>
      </main>
    </div>
  );
};

export default Home;
